services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    environment:
      - DOCKER_API_VERSION=1.40
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8082:8080" # Panel de control de Traefik en http://localhost:8082
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - media

  jellyfin:
    image: jellyfin/jellyfin:10.11.8
    container_name: jellyfin
    user: 1000:1000
    ports:
      - "8096:8096"
    volumes:
      - ./config/jellyfin:/config
      - ./cache:/cache
      - ./media:/media
    restart: unless-stopped
    networks:
      - media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`j.localhost`) || PathPrefix(`/`)"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "7878:7878"
    volumes:
      - ./config/radarr:/config
      - ./media:/media
      - ./downloads:/downloads
    restart: unless-stopped
    networks:
      - media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`r.localhost`)"
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "8080:8080"
    volumes:
      - ./config/qbittorrent:/config
      - ./downloads:/downloads
    restart: unless-stopped
    networks:
      - media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`q.localhost`)"
      - "traefik.http.routers.qbittorrent.entrypoints=web"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "9696:9696"
    volumes:
      - ./config/prowlarr:/config
    restart: unless-stopped
    networks:
      - media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`p.localhost`)"
      - "traefik.http.routers.prowlarr.entrypoints=web"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"

networks:
  media:
    name: media
